services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: usagi-test-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q check_running
      interval: 2s
      timeout: 5s
      retries: 15
